# Generated by Django 3.1.5 on 2021-01-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='messageText',
        ),
    ]
